project:
  type: website
  output-dir: docs

website:
  title: "Yanchen Jiang (Jeff Jiang)"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications & Projects
      - href: contact.qmd
        text: Contact
      - href: doc/yanchenjiang_CV.pdf
        text: CV

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual