---
title: "Publications & Projects"
editor: visual
---

[*Google Scholar Profile.*](https://scholar.google.com/citations?user=ULefWRkAAAAJ&hl=en)

## Academic Publications

*\* indicates equal contribution, (*$\alpha$-$\beta$) indicates alphabetical author order.

#### Selected Conference Publications:

[**1. Duality for Optimal Multi-Item, Multi-Bidder Auction Design: Revenue Certificates through Deep Learning**]{style="color:darkblue"} <br> **Yanchen Jiang**, David C. Parkes, Tonghan Wang. <br> The Twenty-Seventh ACM Conference on Economics and Computation (EC'26). [Preprint](https://arxiv.org/abs/2606.10112).

[**2. Incentive-Aligned Multi-Source LLM Summaries**]{style="color:darkblue"} <br> **Yanchen Jiang**, Zhe Feng, Aranyak Mehta. <br> ICLR 2026. [Preprint](https://arxiv.org/abs/2509.25184).

[**3. BundleFlow: Deep Menus for Combinatorial Auctions by Diffusion-Based Optimization**]{style="color:darkblue"} <br> Tonghan Wang, **Yanchen Jiang**, David C. Parkes. <br> NeurIPS 2025 [Preprint](https://arxiv.org/abs/2502.15283).

[**4. GemNet: Menu-Based, Strategy-Proof Multi-Bidder Auctions Through Deep Learning**]{style="color:darkblue"} <br> Tonghan Wang\*, **Yanchen Jiang\*** , David C. Parkes. <br>The Twenty-Fifth ACM Conference on Economics and Computation (EC'24), [Publication](https://dl.acm.org/doi/10.1145/3670865.3673454), [Preprint](https://arxiv.org/abs/2406.07428). <br> [**Won *Exemplary Paper Award* (awarded to the best paper in track) for the AI track, presented at the Best EC 24 papers plenary session.**]{style="color:darkred;background-color: yellow"}

[**5. Data Market Design through Deep Learning**]{style="color:darkblue"} <br> Sai Srivatsa Ravindranath\*, **Yanchen Jiang\*** , David C. Parkes. <br>Advances in Neural Information Processing Systems 36 (NeurIPS 2023). [Publication](https://proceedings.neurips.cc/paper_files/paper/2023/hash/1577ea3eaf8dacb99f64e4496c3ecddf-Abstract-Conference.html), [Preprint](https://arxiv.org/abs/2310.20096).

#### Other Conference Publications:

[**1. On Diffusion Models for Multi-Agent Partial Observability: Shared Attractors, Error Bounds, and Composite Flow**]{style="color:darkblue"} <br> Tonghan Wang\*, Heng Dong\*, **Yanchen Jiang**, David C. Parkes, Milind Tambe. <br>24th International Conference on Autonomous Agents and Multiagent Systems (AAMAS 2025), [Preprint](https://arxiv.org/abs/2410.13953).

#### Consortium Publications:

[**1. AI-assisted teams outperform AI-led teams but not human-only teams in assessing research reproducibility in quantitative social science**]{style="color:darkblue"} <br> Abel Brodeur, et al. including **Yanchen Jiang**. <br> Proceedings of the National Academy of Sciences 123(22), 2026. [Publication](https://www.pnas.org/doi/abs/10.1073/pnas.2524747123).

[**2. The Prosocial Ranking Challenge: Reducing Polarization on Social Media without Sacrificing Engagement**]{style="color:darkblue"} <br> Jonathan Stray, Ian Baker, George Beknazar-Yuzbashev, Ceren Budak, Julia Kamin, Kylan Rutherford, Mateusz Stalinski, Tin Acosta, Chris Bail, Michael Bernstein, Mark Brandt, Amy Bruckman, Anshuman Chhabra, Soham De, Kayla Duskin, Sara Fish, Beth Goldberg, Andy Guess, Dylan Hadfield-Menell, Muhammed Haroon, Safwan Hossain, Michael Inzlicht, Gauri Jain, **Yanchen Jiang**, et al. <br> arXiv preprint arXiv:2603.19626, 2026. [Preprint](https://arxiv.org/pdf/2603.19626).


#### Workshop and Exhibition Papers:

[**1. Charting the Shapes of Stories with Game Theory**]{style="color:darkblue"} <br> ($\alpha$-$\beta$) Constantinos Daskalakis, Ian Gemp, **Yanchen Jiang**, Renato Paes Leme, Christos Papadimitriou, Georgios Piliouras. <br>[Preprint](https://arxiv.org/abs/2412.05747), [NeurIPS 2024 Creative AI](https://neurips.cc/virtual/2024/105446).

[**2. Evidence from the Synthetic Laboratory: Language Models as Auction Participants**]{style="color:darkblue"} <br>Anand Shah\*, Kehang Zhu\*, **Yanchen Jiang**, Kerem Dayi, Jeffery Wang, John J. Horton, David C. Parkes. <br> EC'24 contributed poster session; NeurIPS 2024 Workshop on Behavioral Machine Learning. [Preprint](https://openreview.net/pdf?id=FB9mTtJpJI).

#### Preprints and Working Papers:

[**1. One Model, Two Markets: Bid-Aware Generative Recommendation**]{style="color:darkblue"} <br> **Yanchen Jiang**, Zhe Feng, Christopher P. Mah, Aranyak Mehta, Di Wang <br> arXiv [Preprint](https://arxiv.org/abs/2603.22231v1).

[**2. LLM Active Alignment: A Nash Equilibrium Perspective**]{style="color:darkblue"} <br> Tonghan Wang, Yuqi Pan, Xinyi Yang, **Yanchen Jiang**, Milind Tambe, David C. Parkes. <br> arXiv [Preprint](https://arxiv.org/abs/2602.06836).


[**3. LLM-Powered Preference Elicitation in Combinatorial Assignment**]{style="color:darkblue"} <br> Ermis Soumalias\*, **Yanchen Jiang\***, Kehang Zhu\*, Michael Curry, Sven Seuken, David C. Parkes. <br> arXiv [Preprint](https://arxiv.org/abs/2502.10308).

#### Survey Papers and Research Letters:

[**1. Automated Mechanism Design: A Survey**]{style="color:darkblue"} <br> Michael J. Curry, Zhou Fan, **Yanchen Jiang**, Sai Srivatsa Ravindranath, Tonghan Wang, David C. Parkes. <br> ACM SIGecom Exchanges, volume 22, issue 2, March 2025. [Publication](https://www.sigecom.org/exchanges/volume_22/2/CURRY.pdf).